spring:
#  jms:
#    pub-sub-domain: true
#    activemq:
#    broker-url: tcp://156.3.12.200:61616
#    user: system
#    password: admin123
  datasource:
    url: jdbc:mysql://localhost:3306/gaojianhuitest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
#    data:
#    - classpath:data.sql
    initialization-mode: never
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: false
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        #allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: user
        # 登录密码
        login-password: 123456
      filter:
        slf4j:
          enabled: true
  data:
    redis:
      repositories:
        enabled: false #避免出现Multiple Spring Data modules found
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: MYSQL
    hibernate:
      ddl-auto: update #create, create-drop, update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: SanYi-NewPlatform
    # servlet 配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
     # redis 缓存
     # redis 缓存
  cache:
    type: redis
    redis:
      time-to-live: 3600000 #过期时间
  redis:
#    host: 112.125.25.247
    host: 192.168.0.51
#    password: 111111
    password: Password123
    port: 6379
    lettuce:
      pool:
         # 最大空闲连接数
        max-idle: 500
         # 最小空闲连接数
        min-idle: 50
         # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
         # 最大活跃连接数，负数为不限制
        max-active: -1
      
# mybatis配置
mybatis:
  mapper-locations:
  - classpath*:mapper/**/*.xml
  type-handlers-package: com.system.framework.mybatisTypeHandler
  type-aliases-package: com.system.framework.model
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

# mybatis 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

          
# 服务端配置
server:
  port: 8080
  tomcat:
    accept-count: 1000
    max-connections: 20000
    max-threads: 2000
  connection-timeout: 20000
  max-http-header-size: 1MB
    
  # 热启动(2019-8-6 17:01:30添加)
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**

#logging:
#  config: classpath*:log4j2-dev.xml
#logging:
#  level:
#    root: info
#    com.system: debug
#  pattern:
#    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'

#jwt 配置 
jwt: 
  header: Authorization
  secret: SanYiSecret
  expiration: 604800
  route: 
    authentication: 
      path: user/auth
      refresh: refresh
    
# 静态资源地址
assets: 
  piclocation: imgs/

system: 
  properties:
    name: MINE管理平台
    description: 系统描述
  enableswagger: false


jackrabbit:
  uri: http://47.93.29.226:8125/rmi
  webdav: http://47.93.29.226:8125/repository/default
  username: admin
  password: admin
  enabled: true

init:
  userdefaultpassword: 111111